version: "3"
services:

    frontend:
        build:
            context: .
        ports:
            - "8080:8080"

    backend:
        build:
            context: .
        ports:
            - "8000:8000"
        env_file:
            -   .env
        depends_on:
            - db
        volumes:
            - ./attachments/files:/app/attachments/files
            - ./attachments/images:/app/attachments/images
        command: >
            sh -c "python manage.py wait_for_db &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:14-alpine
        ports:
            - "5433:5432"
        env_file:
            -   .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
