version: "3"

services:
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - ./frontend/.env
        command: npm run serve
        entrypoint: npm run start

    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            -   .env
        depends_on:
            - db
        volumes:
            - ./backend:/app
            - ./backend/attachments/files:/app/attachments/files
            - ./backend/attachments/images:/app/attachments/images
        command: >
            sh -c "python manage.py wait_for_db &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres:14-alpine
        ports:
            - "5433:5432"
        env_file:
            -   .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
