# Generated by Django 4.2.1 on 2023-05-23 21:30

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="file_type",
        ),
        migrations.AddField(
            model_name="attachment",
            name="image",
            field=models.ImageField(
                null=True, upload_to=comments.models.create_custom_path_image
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                null=True, upload_to=comments.models.create_custom_path_file
            ),
        ),
    ]
