# Generated by Django 4.2.1 on 2023-05-24 10:58

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_remove_attachment_file_type_attachment_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(
                null=True, upload_to=comments.models.create_custom_path_file
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                null=True, upload_to=comments.models.create_custom_path_image
            ),
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
