# Generated by Django 4.2.1 on 2023-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_alter_comment_captcha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="captcha",
            field=models.CharField(max_length=2047),
        ),
    ]
